class ErrorCode:
    BOOKING_NOT_FOUND = "BOOKING_NOT_FOUND"
    INVALID_STATUS = "INVALID_STATUS"
    INVALID_TRANSITION = "INVALID_STATUS_TRANSITION"
    SLOT_CONFLICT = "SLOT_CONFLICT"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_SERVER_ERROR"